# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DelimitedtextPathfixer
                                 A QGIS plugin
 This plugins fixes paths from text/ csv datasources that have not been correctly upgraded
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-18
        copyright            : (C) 2022 by Marco Lechner, RN1, Bundesamt für Strahlenschutz
        email                : mlechner@bfs.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DelimitedtextPathfixer class from file DelimitedtextPathfixer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .delimitedtext_pathfixer import DelimitedtextPathfixer
    return DelimitedtextPathfixer(iface)
